import { StyleSheet } from 'react-native'
import { responsive } from '../utils/responsive'

const PlatListStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FAF1E2',
  },
  headerContainer: {
    backgroundColor: '#E53E3E',
  },
  container: {
    flex: 1,
    backgroundColor: '#FAF1E2',

    paddingVertical: responsive.spacing(8, 12, 16),
  },
  searchContainer: {
    paddingHorizontal: responsive.edgeInsets(12, 16, 20),
    paddingVertical: responsive.spacing(8, 12, 16),
    backgroundColor: '#FAF1E2',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: responsive.borderRadius(8),
    paddingHorizontal: responsive.responsivePadding(12),
    paddingVertical: responsive.responsivePadding(8),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  searchIcon: {
    marginRight: responsive.responsiveMargin(8),
  },
  searchInput: {
    flex: 1,
    height: responsive.scaledSize(40),
    fontSize: responsive.fontSize(14, 16, 18),
    color: '#333',
    outlineWidth: 0,
  },
  listContainer: {
    paddingHorizontal: responsive.edgeInsets(12, 16, 20),
    paddingBottom: responsive.spacing(70, 80, 90),
    width: '100%',
    maxWidth: responsive.adaptiveWidth(100, 80),
    alignSelf: 'center',
  },
  vehicleCard: {
    backgroundColor: '#FDD100',
    borderRadius: responsive.borderRadius(12),
    paddingVertical: responsive.responsivePadding(16),
    paddingHorizontal: responsive.responsivePadding(16),
    marginBottom: responsive.responsiveMargin(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  vehicleContent: {
    marginBottom: responsive.responsiveMargin(8),
  },
  plateNumber: {
    fontSize: responsive.fontSize(18, 20, 22),
    fontWeight: 'bold',
    color: '#000',
    marginBottom: responsive.responsiveMargin(4),
  },
  vehicleType: {
    fontSize: responsive.fontSize(14, 16, 18),
    color: '#000',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: responsive.spacing(6, 8, 10),
    marginTop: responsive.responsiveMargin(8),
  },
  editButton: {
    backgroundColor: '#007D4B',
    paddingVertical: responsive.responsivePadding(8),
    paddingHorizontal: responsive.responsivePadding(20),
    borderRadius: responsive.borderRadius(4),
  },
  editButtonText: {
    color: '#FFFFFF',
    fontWeight: '500',
    fontSize: responsive.fontSize(12, 14, 16),
  },
  deleteButton: {
    backgroundColor: '#E53E3E',
    paddingVertical: responsive.responsivePadding(8),
    paddingHorizontal: responsive.responsivePadding(20),
    borderRadius: responsive.borderRadius(4),
  },
  deleteButtonText: {
    color: '#FFFFFF',
    fontWeight: '500',
    fontSize: responsive.fontSize(12, 14, 16),
  },
  addButton: {
    position: 'absolute',
    bottom: responsive.responsiveMargin(24),
    right: responsive.responsiveMargin(24),
    backgroundColor: '#007D4B',
    width: responsive.scaledSize(56),
    height: responsive.scaledSize(56),
    borderRadius: responsive.scaledSize(28),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: responsive.responsiveMargin(16),
    fontSize: responsive.fontSize(14, 16, 18),
    color: '#333',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: responsive.edgeInsets(24, 32, 40),
  },
  emptyText: {
    fontSize: responsive.fontSize(16, 18, 20),
    fontWeight: 'bold',
    color: '#333',
    marginTop: responsive.responsiveMargin(16),
  },
  emptySubText: {
    fontSize: responsive.fontSize(12, 14, 16),
    color: '#666',
    marginTop: responsive.responsiveMargin(8),
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: responsive.edgeInsets(12, 16, 20),
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: responsive.borderRadius(12),
    width: '100%',
    maxWidth: responsive.adaptiveWidth(90, 70),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalHeaderHapus: {
    backgroundColor: '#E53E3E',
    paddingVertical: responsive.responsivePadding(16),
    paddingHorizontal: responsive.responsivePadding(16),
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  modalTitleHapus: {
    fontSize: responsive.fontSize(16, 18, 20),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  modalHeaderEdit: {
    backgroundColor: '#007D4B',
    paddingVertical: responsive.responsivePadding(16),
    paddingHorizontal: responsive.responsivePadding(16),
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  modalTitleEdit: {
    fontSize: responsive.fontSize(16, 18, 20),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  modalBody: {
    padding: responsive.responsivePadding(20),
    alignItems: 'center',
  },
  warningIcon: {
    marginBottom: responsive.responsiveMargin(16),
  },
  modalMessage: {
    fontSize: responsive.fontSize(14, 16, 18),
    color: '#333',
    textAlign: 'center',
    marginBottom: responsive.responsiveMargin(16),
  },
  vehicleInfoContainer: {
    backgroundColor: '#FAF1E2',
    padding: responsive.responsivePadding(12),
    borderRadius: responsive.borderRadius(8),
    width: '100%',
    alignItems: 'center',
  },
  confirmPlateNumber: {
    fontSize: responsive.fontSize(16, 18, 20),
    fontWeight: 'bold',
    color: '#000',
  },
  confirmVehicleType: {
    fontSize: responsive.fontSize(12, 14, 16),
    color: '#333',
    marginTop: responsive.responsiveMargin(4),
  },
  modalFooter: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  cancelButton: {
    flex: 1,
    paddingVertical: responsive.responsivePadding(16),
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRightWidth: 0.5,
    borderRightColor: '#E0E0E0',
  },
  cancelButtonText: {
    fontSize: responsive.fontSize(14, 16, 18),
    fontWeight: '500',
    color: '#666',
  },
  confirmButton: {
    flex: 1,
    paddingVertical: responsive.responsivePadding(16),
    alignItems: 'center',
    backgroundColor: '#E53E3E',
    borderLeftWidth: 0.5,
    borderLeftColor: '#E0E0E0',
  },
  confirmButtonText: {
    fontSize: responsive.fontSize(14, 16, 18),
    fontWeight: '500',
    color: '#FFFFFF',
  },
  formModalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: responsive.borderRadius(12),
    width: '100%',
    maxWidth: responsive.adaptiveWidth(90, 70),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  formModalContainerSmall: {
    maxWidth: '95%',
  },
  formModalBody: {
    padding: responsive.responsivePadding(20),
  },
  formGroup: {
    marginBottom: responsive.responsiveMargin(16),
  },
  formLabel: {
    fontSize: responsive.fontSize(14, 16, 18),
    fontWeight: '500',
    color: '#333',
    marginBottom: responsive.responsiveMargin(8),
  },
  formInput: {
    backgroundColor: '#F5F5F5',
    borderRadius: responsive.borderRadius(8),
    padding: responsive.responsivePadding(12),
    fontSize: responsive.fontSize(14, 16, 18),
    borderWidth: 1,
    borderColor: '#E0E0E0',
    minHeight: responsive.scaledSize(48),
  },
  inputError: {
    borderColor: '#E53E3E',
  },
  errorText: {
    color: '#E53E3E',
    fontSize: responsive.fontSize(12, 14, 16),
    marginTop: responsive.responsiveMargin(4),
  },
  saveButton: {
    flex: 1,
    paddingVertical: responsive.responsivePadding(16),
    alignItems: 'center',
    backgroundColor: '#007D4B',
    borderLeftWidth: 0.5,
    borderLeftColor: '#E0E0E0',
  },
  saveButtonText: {
    fontSize: responsive.fontSize(14, 16, 18),
    fontWeight: '500',
    color: '#FFFFFF',
  },
})

export default PlatListStyles
